apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  securityContext:
    runAsUser: 1080
    runAsGroup: 3000
  containers:
  - name: sec-busybox
    image: busybox
    command: [ "sh", "-c", "sleep 1h" ]
