apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: nginx:latest
    name: nginx
    env:
    - name: SPECIAL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: special-password
          key: dbpass