apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: nginx
spec:
  containers:
  - image: nginx:latest  
    name: nginx
    volumeMounts:
    - mountPath: /data
      name: demo
  volumes:
  - name: demo
    persistentVolumeClaim:
      claimName: demo-pvc