apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: nginx-dev
spec:
  containers:
  - image: nginx:latest  
    name: nginx-dev
    volumeMounts:
    - mountPath: /data
      name: demo
  volumes:
  - name: demo
    configMap:
      name: demo-dev